language: en
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!**/*.md"
    - "!docs/**"
    - "!.github/**"
    - "!docker-compose.yml"
    - "!Makefile"
chat:
  auto_reply: true
